spring.application.name=device
# Configurare server
server.port=8082

# Configurare MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/device3
spring.datasource.username=root
spring.datasource.password=Emipolicluj1999!
spring.jpa.hibernate.ddl-auto=update
